# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\grl6abt\Coding_Projects\TaskForce301\resources\ui\addShip.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FleetSetUp(object):
    def setupUi(self, FleetSetUp):
        FleetSetUp.setObjectName("FleetSetUp")
        FleetSetUp.resize(812, 660)
        FleetSetUp.setMinimumSize(QtCore.QSize(812, 660))
        FleetSetUp.setMaximumSize(QtCore.QSize(812, 660))
        self.verticalLayoutWidget = QtWidgets.QWidget(FleetSetUp)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(470, 10, 331, 601))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.fleet_lyt = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.fleet_lyt.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.fleet_lyt.setContentsMargins(0, 0, 0, 0)
        self.fleet_lyt.setObjectName("fleet_lyt")
        self.fleet_lbl = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fleet_lbl.setFont(font)
        self.fleet_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.fleet_lbl.setObjectName("fleet_lbl")
        self.fleet_lyt.addWidget(self.fleet_lbl)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ships_in_fleet_lbl = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ships_in_fleet_lbl.setFont(font)
        self.ships_in_fleet_lbl.setObjectName("ships_in_fleet_lbl")
        self.horizontalLayout_7.addWidget(self.ships_in_fleet_lbl)
        self.cur_fleet_cost_lbl = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cur_fleet_cost_lbl.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.cur_fleet_cost_lbl.setObjectName("cur_fleet_cost_lbl")
        self.horizontalLayout_7.addWidget(self.cur_fleet_cost_lbl)
        self.fleet_lyt.addLayout(self.horizontalLayout_7)
        self.listView = QtWidgets.QListView(self.verticalLayoutWidget)
        self.listView.setObjectName("listView")
        self.fleet_lyt.addWidget(self.listView)
        self.del_ship_lyt = QtWidgets.QHBoxLayout()
        self.del_ship_lyt.setObjectName("del_ship_lyt")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.del_ship_lyt.addItem(spacerItem)
        self.del_ship_but = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.del_ship_but.setObjectName("del_ship_but")
        self.del_ship_lyt.addWidget(self.del_ship_but)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.del_ship_lyt.addItem(spacerItem1)
        self.fleet_lyt.addLayout(self.del_ship_lyt)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(FleetSetUp)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 630, 791, 25))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.main_choices_lyt = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.main_choices_lyt.setContentsMargins(0, 0, 0, 0)
        self.main_choices_lyt.setObjectName("main_choices_lyt")
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.main_choices_lyt.addItem(spacerItem2)
        self.clear_fleet_but = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.clear_fleet_but.setObjectName("clear_fleet_but")
        self.main_choices_lyt.addWidget(self.clear_fleet_but)
        self.load_fleet_but = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.load_fleet_but.setObjectName("load_fleet_but")
        self.main_choices_lyt.addWidget(self.load_fleet_but)
        self.save_fleet_but = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.save_fleet_but.setObjectName("save_fleet_but")
        self.main_choices_lyt.addWidget(self.save_fleet_but)
        self.battle_but = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.battle_but.setObjectName("battle_but")
        self.main_choices_lyt.addWidget(self.battle_but)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(FleetSetUp)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(9, 9, 434, 601))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.ship_creator_lyt = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.ship_creator_lyt.setContentsMargins(0, 0, 0, 0)
        self.ship_creator_lyt.setObjectName("ship_creator_lyt")
        self.ship_creator_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ship_creator_lbl.setFont(font)
        self.ship_creator_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ship_creator_lbl.setObjectName("ship_creator_lbl")
        self.ship_creator_lyt.addWidget(self.ship_creator_lbl)
        self.type_select_lyt = QtWidgets.QVBoxLayout()
        self.type_select_lyt.setObjectName("type_select_lyt")
        self.type_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.type_lbl.setFont(font)
        self.type_lbl.setObjectName("type_lbl")
        self.type_select_lyt.addWidget(self.type_lbl)
        self.type_choices_lyt = QtWidgets.QVBoxLayout()
        self.type_choices_lyt.setObjectName("type_choices_lyt")
        self.type_buttons_lyt = QtWidgets.QHBoxLayout()
        self.type_buttons_lyt.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.type_buttons_lyt.setObjectName("type_buttons_lyt")
        self.pt_but = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pt_but.setObjectName("pt_but")
        self.type_buttons_lyt.addWidget(self.pt_but)
        self.dd_but = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.dd_but.setObjectName("dd_but")
        self.type_buttons_lyt.addWidget(self.dd_but)
        self.ca_but = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.ca_but.setObjectName("ca_but")
        self.type_buttons_lyt.addWidget(self.ca_but)
        self.bb_but = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.bb_but.setObjectName("bb_but")
        self.type_buttons_lyt.addWidget(self.bb_but)
        self.type_choices_lyt.addLayout(self.type_buttons_lyt)
        self.type_select_lyt.addLayout(self.type_choices_lyt)
        self.cur_type_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.cur_type_lbl.setMaximumSize(QtCore.QSize(430, 16777215))
        self.cur_type_lbl.setTextFormat(QtCore.Qt.PlainText)
        self.cur_type_lbl.setObjectName("cur_type_lbl")
        self.type_select_lyt.addWidget(self.cur_type_lbl)
        self.ship_creator_lyt.addLayout(self.type_select_lyt)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.ship_creator_lyt.addItem(spacerItem3)
        self.tech_lyt = QtWidgets.QVBoxLayout()
        self.tech_lyt.setObjectName("tech_lyt")
        self.techs_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.techs_lbl.setFont(font)
        self.techs_lbl.setObjectName("techs_lbl")
        self.tech_lyt.addWidget(self.techs_lbl)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gun_tech_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gun_tech_lbl.setFont(font)
        self.gun_tech_lbl.setObjectName("gun_tech_lbl")
        self.gridLayout.addWidget(self.gun_tech_lbl, 0, 0, 1, 1)
        self.rdr_tech_0 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rdr_tech_0.setObjectName("rdr_tech_0")
        self.gridLayout.addWidget(self.rdr_tech_0, 2, 1, 1, 1)
        self.fc_tech_0 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.fc_tech_0.setObjectName("fc_tech_0")
        self.gridLayout.addWidget(self.fc_tech_0, 1, 1, 1, 1)
        self.gun_tech_1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.gun_tech_1.setObjectName("gun_tech_1")
        self.gridLayout.addWidget(self.gun_tech_1, 0, 2, 1, 1)
        self.rdr_tech_1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rdr_tech_1.setObjectName("rdr_tech_1")
        self.gridLayout.addWidget(self.rdr_tech_1, 2, 2, 1, 1)
        self.fc_tech_1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.fc_tech_1.setObjectName("fc_tech_1")
        self.gridLayout.addWidget(self.fc_tech_1, 1, 2, 1, 1)
        self.radar_tech_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radar_tech_lbl.setFont(font)
        self.radar_tech_lbl.setObjectName("radar_tech_lbl")
        self.gridLayout.addWidget(self.radar_tech_lbl, 2, 0, 1, 1)
        self.fc_tech_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fc_tech_lbl.setFont(font)
        self.fc_tech_lbl.setObjectName("fc_tech_lbl")
        self.gridLayout.addWidget(self.fc_tech_lbl, 1, 0, 1, 1)
        self.gun_tech_0 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.gun_tech_0.setObjectName("gun_tech_0")
        self.gridLayout.addWidget(self.gun_tech_0, 0, 1, 1, 1)
        self.gun_tech_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.gun_tech_2.setObjectName("gun_tech_2")
        self.gridLayout.addWidget(self.gun_tech_2, 0, 3, 1, 1)
        self.fc_tech_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.fc_tech_2.setObjectName("fc_tech_2")
        self.gridLayout.addWidget(self.fc_tech_2, 1, 3, 1, 1)
        self.rdr_tech_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rdr_tech_2.setObjectName("rdr_tech_2")
        self.gridLayout.addWidget(self.rdr_tech_2, 2, 3, 1, 1)
        self.tech_lyt.addLayout(self.gridLayout)
        self.ship_creator_lyt.addLayout(self.tech_lyt)
        spacerItem4 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.ship_creator_lyt.addItem(spacerItem4)
        self.ship_stats_lyt = QtWidgets.QVBoxLayout()
        self.ship_stats_lyt.setObjectName("ship_stats_lyt")
        self.ship_stats_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ship_stats_lbl.setFont(font)
        self.ship_stats_lbl.setObjectName("ship_stats_lbl")
        self.ship_stats_lyt.addWidget(self.ship_stats_lbl)
        self.ship_stats_lyt_2 = QtWidgets.QHBoxLayout()
        self.ship_stats_lyt_2.setObjectName("ship_stats_lyt_2")
        self.ship_stats_lyt_3 = QtWidgets.QVBoxLayout()
        self.ship_stats_lyt_3.setObjectName("ship_stats_lyt_3")
        self.general_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.general_label.setFont(font)
        self.general_label.setObjectName("general_label")
        self.ship_stats_lyt_3.addWidget(self.general_label)
        self.type_lyt = QtWidgets.QHBoxLayout()
        self.type_lyt.setObjectName("type_lyt")
        self.type_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.type_label.setObjectName("type_label")
        self.type_lyt.addWidget(self.type_label)
        self.ship_type_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ship_type_label.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.ship_type_label.setObjectName("ship_type_label")
        self.type_lyt.addWidget(self.ship_type_label)
        self.ship_stats_lyt_3.addLayout(self.type_lyt)
        self.name_lyt = QtWidgets.QHBoxLayout()
        self.name_lyt.setObjectName("name_lyt")
        self.name_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.name_label.setObjectName("name_label")
        self.name_lyt.addWidget(self.name_label)
        self.ship_name_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ship_name_label.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.ship_name_label.setObjectName("ship_name_label")
        self.name_lyt.addWidget(self.ship_name_label)
        self.ship_stats_lyt_3.addLayout(self.name_lyt)
        self.len_lyt = QtWidgets.QHBoxLayout()
        self.len_lyt.setObjectName("len_lyt")
        self.length_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.length_lbl.setObjectName("length_lbl")
        self.len_lyt.addWidget(self.length_lbl)
        self.ship_length_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ship_length_lbl.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.ship_length_lbl.setObjectName("ship_length_lbl")
        self.len_lyt.addWidget(self.ship_length_lbl)
        self.ship_stats_lyt_3.addLayout(self.len_lyt)
        self.widht_layout = QtWidgets.QHBoxLayout()
        self.widht_layout.setObjectName("widht_layout")
        self.width_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.width_lbl.setObjectName("width_lbl")
        self.widht_layout.addWidget(self.width_lbl)
        self.ship_width_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ship_width_lbl.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.ship_width_lbl.setObjectName("ship_width_lbl")
        self.widht_layout.addWidget(self.ship_width_lbl)
        self.ship_stats_lyt_3.addLayout(self.widht_layout)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.ship_stats_lyt_3.addWidget(self.line)
        self.weapons_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.weapons_lbl.setFont(font)
        self.weapons_lbl.setObjectName("weapons_lbl")
        self.ship_stats_lyt_3.addWidget(self.weapons_lbl)
        self.main_guns_lyt = QtWidgets.QHBoxLayout()
        self.main_guns_lyt.setObjectName("main_guns_lyt")
        self.ship_mg_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ship_mg_lbl.setObjectName("ship_mg_lbl")
        self.main_guns_lyt.addWidget(self.ship_mg_lbl)
        self.ship_w_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ship_w_lbl.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.ship_w_lbl.setObjectName("ship_w_lbl")
        self.main_guns_lyt.addWidget(self.ship_w_lbl)
        self.ship_stats_lyt_3.addLayout(self.main_guns_lyt)
        self.acc_lyt = QtWidgets.QHBoxLayout()
        self.acc_lyt.setObjectName("acc_lyt")
        self.acc_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.acc_lbl.setObjectName("acc_lbl")
        self.acc_lyt.addWidget(self.acc_lbl)
        self.ship_acc_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ship_acc_lbl.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.ship_acc_lbl.setObjectName("ship_acc_lbl")
        self.acc_lyt.addWidget(self.ship_acc_lbl)
        self.ship_stats_lyt_3.addLayout(self.acc_lyt)
        self.fc_lyt = QtWidgets.QHBoxLayout()
        self.fc_lyt.setObjectName("fc_lyt")
        self.fc_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.fc_lbl.setObjectName("fc_lbl")
        self.fc_lyt.addWidget(self.fc_lbl)
        self.ship_fc_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ship_fc_lbl.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.ship_fc_lbl.setObjectName("ship_fc_lbl")
        self.fc_lyt.addWidget(self.ship_fc_lbl)
        self.ship_stats_lyt_3.addLayout(self.fc_lyt)
        self.err_reduc_lyt = QtWidgets.QHBoxLayout()
        self.err_reduc_lyt.setObjectName("err_reduc_lyt")
        self.err_reduc_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.err_reduc_lbl.setObjectName("err_reduc_lbl")
        self.err_reduc_lyt.addWidget(self.err_reduc_lbl)
        self.ship_errreduc_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ship_errreduc_lbl.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.ship_errreduc_lbl.setObjectName("ship_errreduc_lbl")
        self.err_reduc_lyt.addWidget(self.ship_errreduc_lbl)
        self.ship_stats_lyt_3.addLayout(self.err_reduc_lyt)
        self.ship_stats_lyt_2.addLayout(self.ship_stats_lyt_3)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.ship_stats_lyt_2.addWidget(self.line_4)
        self.hull_stats_lyt = QtWidgets.QVBoxLayout()
        self.hull_stats_lyt.setObjectName("hull_stats_lyt")
        self.hull_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hull_label.setFont(font)
        self.hull_label.setObjectName("hull_label")
        self.hull_stats_lyt.addWidget(self.hull_label)
        self.hp_lyt = QtWidgets.QHBoxLayout()
        self.hp_lyt.setObjectName("hp_lyt")
        self.max_hp_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.max_hp_lbl.setObjectName("max_hp_lbl")
        self.hp_lyt.addWidget(self.max_hp_lbl)
        self.ship_max_hp_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ship_max_hp_lbl.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.ship_max_hp_lbl.setObjectName("ship_max_hp_lbl")
        self.hp_lyt.addWidget(self.ship_max_hp_lbl)
        self.hull_stats_lyt.addLayout(self.hp_lyt)
        self.armor_lyt = QtWidgets.QHBoxLayout()
        self.armor_lyt.setObjectName("armor_lyt")
        self.armor_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.armor_lbl.setObjectName("armor_lbl")
        self.armor_lyt.addWidget(self.armor_lbl)
        self.ship_armor_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ship_armor_lbl.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.ship_armor_lbl.setObjectName("ship_armor_lbl")
        self.armor_lyt.addWidget(self.ship_armor_lbl)
        self.hull_stats_lyt.addLayout(self.armor_lyt)
        self.shield_lyt = QtWidgets.QHBoxLayout()
        self.shield_lyt.setObjectName("shield_lyt")
        self.shield_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.shield_lbl.setObjectName("shield_lbl")
        self.shield_lyt.addWidget(self.shield_lbl)
        self.ship_shield_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ship_shield_lbl.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.ship_shield_lbl.setObjectName("ship_shield_lbl")
        self.shield_lyt.addWidget(self.ship_shield_lbl)
        self.hull_stats_lyt.addLayout(self.shield_lyt)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.hull_stats_lyt.addWidget(self.line_2)
        self.mobility_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.mobility_lbl.setFont(font)
        self.mobility_lbl.setObjectName("mobility_lbl")
        self.hull_stats_lyt.addWidget(self.mobility_lbl)
        self.speed_lyt = QtWidgets.QHBoxLayout()
        self.speed_lyt.setObjectName("speed_lyt")
        self.v_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.v_lbl.setObjectName("v_lbl")
        self.speed_lyt.addWidget(self.v_lbl)
        self.ship_v_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ship_v_lbl.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.ship_v_lbl.setObjectName("ship_v_lbl")
        self.speed_lyt.addWidget(self.ship_v_lbl)
        self.hull_stats_lyt.addLayout(self.speed_lyt)
        self.accel_lyt = QtWidgets.QHBoxLayout()
        self.accel_lyt.setObjectName("accel_lyt")
        self.accel_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.accel_lbl.setObjectName("accel_lbl")
        self.accel_lyt.addWidget(self.accel_lbl)
        self.ship_accel_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ship_accel_lbl.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.ship_accel_lbl.setObjectName("ship_accel_lbl")
        self.accel_lyt.addWidget(self.ship_accel_lbl)
        self.hull_stats_lyt.addLayout(self.accel_lyt)
        self.t_rate_lyt = QtWidgets.QHBoxLayout()
        self.t_rate_lyt.setObjectName("t_rate_lyt")
        self.t_rate_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.t_rate_lbl.setObjectName("t_rate_lbl")
        self.t_rate_lyt.addWidget(self.t_rate_lbl)
        self.ship_t_rate_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ship_t_rate_lbl.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.ship_t_rate_lbl.setObjectName("ship_t_rate_lbl")
        self.t_rate_lyt.addWidget(self.ship_t_rate_lbl)
        self.hull_stats_lyt.addLayout(self.t_rate_lyt)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.hull_stats_lyt.addWidget(self.line_3)
        self.vnc_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.vnc_label.setFont(font)
        self.vnc_label.setObjectName("vnc_label")
        self.hull_stats_lyt.addWidget(self.vnc_label)
        self.vision_lyt = QtWidgets.QHBoxLayout()
        self.vision_lyt.setObjectName("vision_lyt")
        self.vision_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.vision_lbl.setObjectName("vision_lbl")
        self.vision_lyt.addWidget(self.vision_lbl)
        self.ship_vision_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ship_vision_lbl.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.ship_vision_lbl.setObjectName("ship_vision_lbl")
        self.vision_lyt.addWidget(self.ship_vision_lbl)
        self.hull_stats_lyt.addLayout(self.vision_lyt)
        self.concl_lyt = QtWidgets.QHBoxLayout()
        self.concl_lyt.setObjectName("concl_lyt")
        self.concl_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.concl_lbl.setObjectName("concl_lbl")
        self.concl_lyt.addWidget(self.concl_lbl)
        self.ship_concl_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ship_concl_lbl.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.ship_concl_lbl.setObjectName("ship_concl_lbl")
        self.concl_lyt.addWidget(self.ship_concl_lbl)
        self.hull_stats_lyt.addLayout(self.concl_lyt)
        self.ship_stats_lyt_2.addLayout(self.hull_stats_lyt)
        self.ship_stats_lyt.addLayout(self.ship_stats_lyt_2)
        self.ship_creator_lyt.addLayout(self.ship_stats_lyt)
        spacerItem5 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.ship_creator_lyt.addItem(spacerItem5)
        self.clear_add_but_lyt = QtWidgets.QHBoxLayout()
        self.clear_add_but_lyt.setObjectName("clear_add_but_lyt")
        self.ship_cost_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ship_cost_lbl.setObjectName("ship_cost_lbl")
        self.clear_add_but_lyt.addWidget(self.ship_cost_lbl)
        self.ship_cost = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ship_cost.setObjectName("ship_cost")
        self.clear_add_but_lyt.addWidget(self.ship_cost)
        spacerItem6 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.clear_add_but_lyt.addItem(spacerItem6)
        self.clear_ship_but = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.clear_ship_but.setObjectName("clear_ship_but")
        self.clear_add_but_lyt.addWidget(self.clear_ship_but)
        self.add_ship_but = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.add_ship_but.setObjectName("add_ship_but")
        self.clear_add_but_lyt.addWidget(self.add_ship_but)
        self.ship_creator_lyt.addLayout(self.clear_add_but_lyt)

        self.retranslateUi(FleetSetUp)
        QtCore.QMetaObject.connectSlotsByName(FleetSetUp)

    def retranslateUi(self, FleetSetUp):
        _translate = QtCore.QCoreApplication.translate
        FleetSetUp.setWindowTitle(_translate("FleetSetUp", "Set up your fleet"))
        self.fleet_lbl.setText(_translate("FleetSetUp", "FLEET"))
        self.ships_in_fleet_lbl.setText(_translate("FleetSetUp", "SHIPS IN FLEET"))
        self.cur_fleet_cost_lbl.setText(_translate("FleetSetUp", "COST / MAX COST"))
        self.del_ship_but.setText(_translate("FleetSetUp", "Delete"))
        self.clear_fleet_but.setText(_translate("FleetSetUp", "Reset Fleet"))
        self.load_fleet_but.setText(_translate("FleetSetUp", "Load Fleet"))
        self.save_fleet_but.setText(_translate("FleetSetUp", "Save Fleet"))
        self.battle_but.setText(_translate("FleetSetUp", "BATTLE !"))
        self.ship_creator_lbl.setText(_translate("FleetSetUp", "SHIP CREATOR"))
        self.type_lbl.setText(_translate("FleetSetUp", "SHIP TYPE:"))
        self.pt_but.setText(_translate("FleetSetUp", "CORVETTE"))
        self.dd_but.setText(_translate("FleetSetUp", "DESTROYER"))
        self.ca_but.setText(_translate("FleetSetUp", "CRUISER"))
        self.bb_but.setText(_translate("FleetSetUp", "BATTLESHIP"))
        self.cur_type_lbl.setText(_translate("FleetSetUp", "Type:"))
        self.techs_lbl.setText(_translate("FleetSetUp", "TECHNOLOGIES LEVEL"))
        self.gun_tech_lbl.setText(_translate("FleetSetUp", "Gun tech"))
        self.rdr_tech_0.setText(_translate("FleetSetUp", "Mk I"))
        self.fc_tech_0.setText(_translate("FleetSetUp", "Mk I"))
        self.gun_tech_1.setText(_translate("FleetSetUp", "Mk II"))
        self.rdr_tech_1.setText(_translate("FleetSetUp", "Mk II"))
        self.fc_tech_1.setText(_translate("FleetSetUp", "Mk II"))
        self.radar_tech_lbl.setText(_translate("FleetSetUp", "Radar tech"))
        self.fc_tech_lbl.setText(_translate("FleetSetUp", "Fire Control tech"))
        self.gun_tech_0.setText(_translate("FleetSetUp", "Mk I"))
        self.gun_tech_2.setText(_translate("FleetSetUp", "Mk III"))
        self.fc_tech_2.setText(_translate("FleetSetUp", "Mk III"))
        self.rdr_tech_2.setText(_translate("FleetSetUp", "Mk III"))
        self.ship_stats_lbl.setText(_translate("FleetSetUp", "SHIP CHARACTERISTICS"))
        self.general_label.setText(_translate("FleetSetUp", "GENERAL"))
        self.type_label.setText(_translate("FleetSetUp", "Type:"))
        self.ship_type_label.setText(_translate("FleetSetUp", "TextLabel"))
        self.name_label.setText(_translate("FleetSetUp", "Name:"))
        self.ship_name_label.setText(_translate("FleetSetUp", "TextLabel"))
        self.length_lbl.setText(_translate("FleetSetUp", "Length"))
        self.ship_length_lbl.setText(_translate("FleetSetUp", "TextLabel"))
        self.width_lbl.setText(_translate("FleetSetUp", "Width"))
        self.ship_width_lbl.setText(_translate("FleetSetUp", "TextLabel"))
        self.weapons_lbl.setText(_translate("FleetSetUp", "WEAPONS"))
        self.ship_mg_lbl.setText(_translate("FleetSetUp", "Main guns"))
        self.ship_w_lbl.setText(_translate("FleetSetUp", "TextLabel"))
        self.acc_lbl.setText(_translate("FleetSetUp", "Guns accuracy"))
        self.ship_acc_lbl.setText(_translate("FleetSetUp", "TextLabel"))
        self.fc_lbl.setText(_translate("FleetSetUp", "Fire control error"))
        self.ship_fc_lbl.setText(_translate("FleetSetUp", "TextLabel"))
        self.err_reduc_lbl.setText(_translate("FleetSetUp", "Error reduction rate"))
        self.ship_errreduc_lbl.setText(_translate("FleetSetUp", "TextLabel"))
        self.hull_label.setText(_translate("FleetSetUp", "HULL"))
        self.max_hp_lbl.setText(_translate("FleetSetUp", "HP:"))
        self.ship_max_hp_lbl.setText(_translate("FleetSetUp", "TextLabel"))
        self.armor_lbl.setText(_translate("FleetSetUp", "Armor:"))
        self.ship_armor_lbl.setText(_translate("FleetSetUp", "TextLabel"))
        self.shield_lbl.setText(_translate("FleetSetUp", "Shield"))
        self.ship_shield_lbl.setText(_translate("FleetSetUp", "TextLabel"))
        self.mobility_lbl.setText(_translate("FleetSetUp", "MOBILITY"))
        self.v_lbl.setText(_translate("FleetSetUp", "Speed"))
        self.ship_v_lbl.setText(_translate("FleetSetUp", "TextLabel"))
        self.accel_lbl.setText(_translate("FleetSetUp", "Acceleration"))
        self.ship_accel_lbl.setText(_translate("FleetSetUp", "TextLabel"))
        self.t_rate_lbl.setText(_translate("FleetSetUp", "Turn rate"))
        self.ship_t_rate_lbl.setText(_translate("FleetSetUp", "TextLabel"))
        self.vnc_label.setText(_translate("FleetSetUp", "VISION & CONCEALMENT"))
        self.vision_lbl.setText(_translate("FleetSetUp", "Vision range"))
        self.ship_vision_lbl.setText(_translate("FleetSetUp", "TextLabel"))
        self.concl_lbl.setText(_translate("FleetSetUp", "Concealment"))
        self.ship_concl_lbl.setText(_translate("FleetSetUp", "TextLabel"))
        self.ship_cost_lbl.setText(_translate("FleetSetUp", "SHIP COST:"))
        self.ship_cost.setText(_translate("FleetSetUp", "00000"))
        self.clear_ship_but.setText(_translate("FleetSetUp", "Reset"))
        self.add_ship_but.setText(_translate("FleetSetUp", "Add Ship"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    FleetSetUp = QtWidgets.QDialog()
    ui = Ui_FleetSetUp()
    ui.setupUi(FleetSetUp)
    FleetSetUp.show()
    sys.exit(app.exec_())

