# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\grl6abt\Coding_Projects\TaskForce301\resources\ui\battleSetup.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_battle_setup(object):
    def setupUi(self, battle_setup):
        battle_setup.setObjectName("battle_setup")
        battle_setup.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(battle_setup)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cancelButton = QtWidgets.QPushButton(battle_setup)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.ok_button = QtWidgets.QPushButton(battle_setup)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.gridLayout.addLayout(self.horizontalLayout, 9, 1, 1, 1)
        self.points_cmbbox = QtWidgets.QComboBox(battle_setup)
        self.points_cmbbox.setObjectName("points_cmbbox")
        self.points_cmbbox.addItem("")
        self.points_cmbbox.addItem("")
        self.points_cmbbox.addItem("")
        self.gridLayout.addWidget(self.points_cmbbox, 7, 1, 1, 1)
        self.difficulty_cmbbox = QtWidgets.QComboBox(battle_setup)
        self.difficulty_cmbbox.setObjectName("difficulty_cmbbox")
        self.difficulty_cmbbox.addItem("")
        self.difficulty_cmbbox.addItem("")
        self.difficulty_cmbbox.addItem("")
        self.difficulty_cmbbox.addItem("")
        self.gridLayout.addWidget(self.difficulty_cmbbox, 3, 1, 1, 1)
        self.map_size_lbl = QtWidgets.QLabel(battle_setup)
        self.map_size_lbl.setObjectName("map_size_lbl")
        self.gridLayout.addWidget(self.map_size_lbl, 1, 0, 1, 1)
        self.funds_cmbbox = QtWidgets.QComboBox(battle_setup)
        self.funds_cmbbox.setObjectName("funds_cmbbox")
        self.funds_cmbbox.addItem("")
        self.funds_cmbbox.addItem("")
        self.funds_cmbbox.addItem("")
        self.funds_cmbbox.addItem("")
        self.gridLayout.addWidget(self.funds_cmbbox, 4, 1, 1, 1)
        self.funds_lbl = QtWidgets.QLabel(battle_setup)
        self.funds_lbl.setObjectName("funds_lbl")
        self.gridLayout.addWidget(self.funds_lbl, 4, 0, 1, 1)
        self.maps_comboBox = QtWidgets.QComboBox(battle_setup)
        self.maps_comboBox.setObjectName("maps_comboBox")
        self.maps_comboBox.addItem("")
        self.maps_comboBox.addItem("")
        self.maps_comboBox.addItem("")
        self.gridLayout.addWidget(self.maps_comboBox, 0, 1, 1, 1)
        self.difficulty_lbl = QtWidgets.QLabel(battle_setup)
        self.difficulty_lbl.setObjectName("difficulty_lbl")
        self.gridLayout.addWidget(self.difficulty_lbl, 3, 0, 1, 1)
        self.v_cond_cmbbox = QtWidgets.QComboBox(battle_setup)
        self.v_cond_cmbbox.setObjectName("v_cond_cmbbox")
        self.v_cond_cmbbox.addItem("")
        self.v_cond_cmbbox.addItem("")
        self.gridLayout.addWidget(self.v_cond_cmbbox, 6, 1, 1, 1)
        self.map_obs_lbl = QtWidgets.QLabel(battle_setup)
        self.map_obs_lbl.setObjectName("map_obs_lbl")
        self.gridLayout.addWidget(self.map_obs_lbl, 2, 0, 1, 1)
        self.v_cond_lbl = QtWidgets.QLabel(battle_setup)
        self.v_cond_lbl.setObjectName("v_cond_lbl")
        self.gridLayout.addWidget(self.v_cond_lbl, 6, 0, 1, 1)
        self.sel_s_map_lbl = QtWidgets.QLabel(battle_setup)
        self.sel_s_map_lbl.setObjectName("sel_s_map_lbl")
        self.gridLayout.addWidget(self.sel_s_map_lbl, 0, 0, 1, 1)
        self.map_size_cmbbox = QtWidgets.QComboBox(battle_setup)
        self.map_size_cmbbox.setObjectName("map_size_cmbbox")
        self.map_size_cmbbox.addItem("")
        self.map_size_cmbbox.addItem("")
        self.map_size_cmbbox.addItem("")
        self.gridLayout.addWidget(self.map_size_cmbbox, 1, 1, 1, 1)
        self.cstm_funds_l_edit = QtWidgets.QLineEdit(battle_setup)
        self.cstm_funds_l_edit.setObjectName("cstm_funds_l_edit")
        self.gridLayout.addWidget(self.cstm_funds_l_edit, 5, 1, 1, 1)
        self.mapObs_cmbbox = QtWidgets.QComboBox(battle_setup)
        self.mapObs_cmbbox.setObjectName("mapObs_cmbbox")
        self.mapObs_cmbbox.addItem("")
        self.mapObs_cmbbox.addItem("")
        self.mapObs_cmbbox.addItem("")
        self.mapObs_cmbbox.addItem("")
        self.gridLayout.addWidget(self.mapObs_cmbbox, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 8, 1, 1, 1)

        self.retranslateUi(battle_setup)
        QtCore.QMetaObject.connectSlotsByName(battle_setup)

    def retranslateUi(self, battle_setup):
        _translate = QtCore.QCoreApplication.translate
        battle_setup.setWindowTitle(_translate("battle_setup", "Game setup"))
        self.cancelButton.setText(_translate("battle_setup", "Cancel"))
        self.ok_button.setText(_translate("battle_setup", "Assemble the Fleet !"))
        self.points_cmbbox.setItemText(0, _translate("battle_setup", "25 %"))
        self.points_cmbbox.setItemText(1, _translate("battle_setup", "50 %"))
        self.points_cmbbox.setItemText(2, _translate("battle_setup", "75 %"))
        self.difficulty_cmbbox.setItemText(0, _translate("battle_setup", "Easy"))
        self.difficulty_cmbbox.setItemText(1, _translate("battle_setup", "Normal"))
        self.difficulty_cmbbox.setItemText(2, _translate("battle_setup", "Hard"))
        self.difficulty_cmbbox.setItemText(3, _translate("battle_setup", "Very Hard"))
        self.map_size_lbl.setText(_translate("battle_setup", "Map size:"))
        self.funds_cmbbox.setItemText(0, _translate("battle_setup", "Small"))
        self.funds_cmbbox.setItemText(1, _translate("battle_setup", "Standard"))
        self.funds_cmbbox.setItemText(2, _translate("battle_setup", "Large"))
        self.funds_cmbbox.setItemText(3, _translate("battle_setup", "Custom"))
        self.funds_lbl.setText(_translate("battle_setup", "Funds:"))
        self.maps_comboBox.setItemText(0, _translate("battle_setup", "Random"))
        self.maps_comboBox.setItemText(1, _translate("battle_setup", "Map 1"))
        self.maps_comboBox.setItemText(2, _translate("battle_setup", "Map 2"))
        self.difficulty_lbl.setText(_translate("battle_setup", "Difficulty:"))
        self.v_cond_cmbbox.setItemText(0, _translate("battle_setup", "Annihilation"))
        self.v_cond_cmbbox.setItemText(1, _translate("battle_setup", "Points"))
        self.map_obs_lbl.setText(_translate("battle_setup", "Map obstruction:"))
        self.v_cond_lbl.setText(_translate("battle_setup", "Victory condition:"))
        self.sel_s_map_lbl.setText(_translate("battle_setup", "Selected Map:"))
        self.map_size_cmbbox.setItemText(0, _translate("battle_setup", "Small"))
        self.map_size_cmbbox.setItemText(1, _translate("battle_setup", "Medium"))
        self.map_size_cmbbox.setItemText(2, _translate("battle_setup", "Large"))
        self.mapObs_cmbbox.setItemText(0, _translate("battle_setup", "Open"))
        self.mapObs_cmbbox.setItemText(1, _translate("battle_setup", "Light"))
        self.mapObs_cmbbox.setItemText(2, _translate("battle_setup", "Medium"))
        self.mapObs_cmbbox.setItemText(3, _translate("battle_setup", "Heavy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    battle_setup = QtWidgets.QDialog()
    ui = Ui_battle_setup()
    ui.setupUi(battle_setup)
    battle_setup.show()
    sys.exit(app.exec_())

