# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\grl6abt\Coding_Projects\TaskForce301\resources\ui\Proto_2.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 920)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 1, 1, 1)
        self.current_ship_frame = QtWidgets.QFrame(self.centralwidget)
        self.current_ship_frame.setMinimumSize(QtCore.QSize(899, 135))
        self.current_ship_frame.setMaximumSize(QtCore.QSize(16777215, 135))
        self.current_ship_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.current_ship_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.current_ship_frame.setObjectName("current_ship_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.current_ship_frame)
        self.verticalLayout_3.setContentsMargins(-1, 9, -1, 9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ship_hp_h_lyt = QtWidgets.QHBoxLayout()
        self.ship_hp_h_lyt.setObjectName("ship_hp_h_lyt")
        self.ship_type_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.ship_type_lbl.setObjectName("ship_type_lbl")
        self.ship_hp_h_lyt.addWidget(self.ship_type_lbl)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ship_hp_h_lyt.addItem(spacerItem2)
        self.ship_name_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.ship_name_lbl.setObjectName("ship_name_lbl")
        self.ship_hp_h_lyt.addWidget(self.ship_name_lbl)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ship_hp_h_lyt.addItem(spacerItem3)
        self.hp_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.hp_lbl.setObjectName("hp_lbl")
        self.ship_hp_h_lyt.addWidget(self.hp_lbl)
        self.hp_progress_bar = QtWidgets.QProgressBar(self.current_ship_frame)
        self.hp_progress_bar.setProperty("value", 24)
        self.hp_progress_bar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.hp_progress_bar.setObjectName("hp_progress_bar")
        self.ship_hp_h_lyt.addWidget(self.hp_progress_bar)
        self.verticalLayout_3.addLayout(self.ship_hp_h_lyt)
        self.displays_h_lyt = QtWidgets.QHBoxLayout()
        self.displays_h_lyt.setObjectName("displays_h_lyt")
        self.gen_stats_v_lyt = QtWidgets.QVBoxLayout()
        self.gen_stats_v_lyt.setObjectName("gen_stats_v_lyt")
        self.stats_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.stats_lbl.setObjectName("stats_lbl")
        self.gen_stats_v_lyt.addWidget(self.stats_lbl)
        self.all_stats_v_lyt = QtWidgets.QVBoxLayout()
        self.all_stats_v_lyt.setObjectName("all_stats_v_lyt")
        self.armor_lyt = QtWidgets.QHBoxLayout()
        self.armor_lyt.setObjectName("armor_lyt")
        self.armor_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.armor_lbl.setObjectName("armor_lbl")
        self.armor_lyt.addWidget(self.armor_lbl)
        self.armor_value_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.armor_value_lbl.setObjectName("armor_value_lbl")
        self.armor_lyt.addWidget(self.armor_value_lbl)
        self.all_stats_v_lyt.addLayout(self.armor_lyt)
        self.g_range_lyt = QtWidgets.QHBoxLayout()
        self.g_range_lyt.setObjectName("g_range_lyt")
        self.gun_range_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.gun_range_lbl.setObjectName("gun_range_lbl")
        self.g_range_lyt.addWidget(self.gun_range_lbl)
        self.gun_range_value_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.gun_range_value_lbl.setObjectName("gun_range_value_lbl")
        self.g_range_lyt.addWidget(self.gun_range_value_lbl)
        self.all_stats_v_lyt.addLayout(self.g_range_lyt)
        self.accuracy_lyt = QtWidgets.QHBoxLayout()
        self.accuracy_lyt.setObjectName("accuracy_lyt")
        self.accuracy_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.accuracy_lbl.setObjectName("accuracy_lbl")
        self.accuracy_lyt.addWidget(self.accuracy_lbl)
        self.accuracy_value_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.accuracy_value_lbl.setObjectName("accuracy_value_lbl")
        self.accuracy_lyt.addWidget(self.accuracy_value_lbl)
        self.all_stats_v_lyt.addLayout(self.accuracy_lyt)
        self.m_d_range_lyt = QtWidgets.QHBoxLayout()
        self.m_d_range_lyt.setObjectName("m_d_range_lyt")
        self.max_det_range_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.max_det_range_lbl.setObjectName("max_det_range_lbl")
        self.m_d_range_lyt.addWidget(self.max_det_range_lbl)
        self.max_det_range_value_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.max_det_range_value_lbl.setObjectName("max_det_range_value_lbl")
        self.m_d_range_lyt.addWidget(self.max_det_range_value_lbl)
        self.all_stats_v_lyt.addLayout(self.m_d_range_lyt)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.all_stats_v_lyt.addItem(spacerItem4)
        self.gen_stats_v_lyt.addLayout(self.all_stats_v_lyt)
        self.displays_h_lyt.addLayout(self.gen_stats_v_lyt)
        self.eng_policy_v_lyt = QtWidgets.QVBoxLayout()
        self.eng_policy_v_lyt.setObjectName("eng_policy_v_lyt")
        self.eng_policy_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.eng_policy_lbl.setObjectName("eng_policy_lbl")
        self.eng_policy_v_lyt.addWidget(self.eng_policy_lbl)
        self.choices_h_lyt = QtWidgets.QHBoxLayout()
        self.choices_h_lyt.setObjectName("choices_h_lyt")
        self.auto_radio_but = QtWidgets.QRadioButton(self.current_ship_frame)
        self.auto_radio_but.setObjectName("auto_radio_but")
        self.choices_h_lyt.addWidget(self.auto_radio_but)
        self.distance_v_lyt = QtWidgets.QVBoxLayout()
        self.distance_v_lyt.setSpacing(6)
        self.distance_v_lyt.setObjectName("distance_v_lyt")
        self.distance_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.distance_lbl.setObjectName("distance_lbl")
        self.distance_v_lyt.addWidget(self.distance_lbl)
        self.long_range_radio_but = QtWidgets.QRadioButton(self.current_ship_frame)
        self.long_range_radio_but.setObjectName("long_range_radio_but")
        self.distance_v_lyt.addWidget(self.long_range_radio_but)
        self.med_range_radio_but = QtWidgets.QRadioButton(self.current_ship_frame)
        self.med_range_radio_but.setObjectName("med_range_radio_but")
        self.distance_v_lyt.addWidget(self.med_range_radio_but)
        self.short_range_radio_but = QtWidgets.QRadioButton(self.current_ship_frame)
        self.short_range_radio_but.setObjectName("short_range_radio_but")
        self.distance_v_lyt.addWidget(self.short_range_radio_but)
        self.choices_h_lyt.addLayout(self.distance_v_lyt)
        self.shot_type_v_lyt = QtWidgets.QVBoxLayout()
        self.shot_type_v_lyt.setObjectName("shot_type_v_lyt")
        self.shot_type_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.shot_type_lbl.setObjectName("shot_type_lbl")
        self.shot_type_v_lyt.addWidget(self.shot_type_lbl)
        self.ap_radio_but = QtWidgets.QRadioButton(self.current_ship_frame)
        self.ap_radio_but.setObjectName("ap_radio_but")
        self.shot_type_v_lyt.addWidget(self.ap_radio_but)
        self.he_radio_but = QtWidgets.QRadioButton(self.current_ship_frame)
        self.he_radio_but.setObjectName("he_radio_but")
        self.shot_type_v_lyt.addWidget(self.he_radio_but)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.shot_type_v_lyt.addItem(spacerItem5)
        self.choices_h_lyt.addLayout(self.shot_type_v_lyt)
        self.eng_policy_v_lyt.addLayout(self.choices_h_lyt)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.eng_policy_v_lyt.addItem(spacerItem6)
        self.displays_h_lyt.addLayout(self.eng_policy_v_lyt)
        self.components_v_lyt = QtWidgets.QVBoxLayout()
        self.components_v_lyt.setObjectName("components_v_lyt")
        self.components_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.components_lbl.setObjectName("components_lbl")
        self.components_v_lyt.addWidget(self.components_lbl)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.components_v_lyt.addItem(spacerItem7)
        self.sub_comp_h_lyt = QtWidgets.QHBoxLayout()
        self.sub_comp_h_lyt.setObjectName("sub_comp_h_lyt")
        self.bridge_h_lyt = QtWidgets.QHBoxLayout()
        self.bridge_h_lyt.setObjectName("bridge_h_lyt")
        self.bridge_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.bridge_lbl.setObjectName("bridge_lbl")
        self.bridge_h_lyt.addWidget(self.bridge_lbl)
        self.bridge_state_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.bridge_state_lbl.setObjectName("bridge_state_lbl")
        self.bridge_h_lyt.addWidget(self.bridge_state_lbl)
        self.sub_comp_h_lyt.addLayout(self.bridge_h_lyt)
        self.engine_h_lyt = QtWidgets.QHBoxLayout()
        self.engine_h_lyt.setObjectName("engine_h_lyt")
        self.engine_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.engine_lbl.setObjectName("engine_lbl")
        self.engine_h_lyt.addWidget(self.engine_lbl)
        self.engine_state_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.engine_state_lbl.setObjectName("engine_state_lbl")
        self.engine_h_lyt.addWidget(self.engine_state_lbl)
        self.sub_comp_h_lyt.addLayout(self.engine_h_lyt)
        self.radar_h_lyt = QtWidgets.QHBoxLayout()
        self.radar_h_lyt.setObjectName("radar_h_lyt")
        self.radar_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.radar_lbl.setObjectName("radar_lbl")
        self.radar_h_lyt.addWidget(self.radar_lbl)
        self.radar_state_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.radar_state_lbl.setObjectName("radar_state_lbl")
        self.radar_h_lyt.addWidget(self.radar_state_lbl)
        self.sub_comp_h_lyt.addLayout(self.radar_h_lyt)
        self.fires_h_lyt = QtWidgets.QHBoxLayout()
        self.fires_h_lyt.setObjectName("fires_h_lyt")
        self.fires_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.fires_lbl.setObjectName("fires_lbl")
        self.fires_h_lyt.addWidget(self.fires_lbl)
        self.nb_fire_lbl = QtWidgets.QLabel(self.current_ship_frame)
        self.nb_fire_lbl.setObjectName("nb_fire_lbl")
        self.fires_h_lyt.addWidget(self.nb_fire_lbl)
        self.sub_comp_h_lyt.addLayout(self.fires_h_lyt)
        self.components_v_lyt.addLayout(self.sub_comp_h_lyt)
        self.repair_but = QtWidgets.QPushButton(self.current_ship_frame)
        self.repair_but.setObjectName("repair_but")
        self.components_v_lyt.addWidget(self.repair_but)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.components_v_lyt.addItem(spacerItem8)
        self.displays_h_lyt.addLayout(self.components_v_lyt)
        self.verticalLayout_3.addLayout(self.displays_h_lyt)
        self.gridLayout.addWidget(self.current_ship_frame, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        self.menuGame = QtWidgets.QMenu(self.menubar)
        self.menuGame.setObjectName("menuGame")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.playerShipsDW = QtWidgets.QDockWidget(MainWindow)
        self.playerShipsDW.setObjectName("playerShipsDW")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listView = QtWidgets.QListView(self.dockWidgetContents)
        self.listView.setObjectName("listView")
        self.gridLayout_2.addWidget(self.listView, 0, 0, 1, 1)
        self.playerShipsDW.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.playerShipsDW)
        self.actionNew_Game = QtWidgets.QAction(MainWindow)
        self.actionNew_Game.setObjectName("actionNew_Game")
        self.menuGame.addAction(self.actionNew_Game)
        self.menubar.addAction(self.menuGame.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "New Game"))
        self.pushButton_3.setText(_translate("MainWindow", "Options"))
        self.pushButton.setText(_translate("MainWindow", "Exit"))
        self.ship_type_lbl.setText(_translate("MainWindow", "SHIP TYPE"))
        self.ship_name_lbl.setText(_translate("MainWindow", "A_VERY_LONG_SHIP_NAME"))
        self.hp_lbl.setText(_translate("MainWindow", "HP:"))
        self.stats_lbl.setText(_translate("MainWindow", "STATS"))
        self.armor_lbl.setText(_translate("MainWindow", "Armor"))
        self.armor_value_lbl.setText(_translate("MainWindow", "000"))
        self.gun_range_lbl.setText(_translate("MainWindow", "Gun Range"))
        self.gun_range_value_lbl.setText(_translate("MainWindow", "00000"))
        self.accuracy_lbl.setText(_translate("MainWindow", "Accuracy"))
        self.accuracy_value_lbl.setText(_translate("MainWindow", "0.000"))
        self.max_det_range_lbl.setText(_translate("MainWindow", "Max Detection Range"))
        self.max_det_range_value_lbl.setText(_translate("MainWindow", "00000"))
        self.eng_policy_lbl.setText(_translate("MainWindow", "ENGAGEMENT POLICY"))
        self.auto_radio_but.setText(_translate("MainWindow", "AUTO"))
        self.distance_lbl.setText(_translate("MainWindow", "Distance"))
        self.long_range_radio_but.setText(_translate("MainWindow", "Long Range"))
        self.med_range_radio_but.setText(_translate("MainWindow", "Medium Range"))
        self.short_range_radio_but.setText(_translate("MainWindow", "Short Range"))
        self.shot_type_lbl.setText(_translate("MainWindow", "Shot Type"))
        self.ap_radio_but.setText(_translate("MainWindow", "AP"))
        self.he_radio_but.setText(_translate("MainWindow", "HE"))
        self.components_lbl.setText(_translate("MainWindow", "COMPONENTS"))
        self.bridge_lbl.setText(_translate("MainWindow", "BRIDGE:"))
        self.bridge_state_lbl.setText(_translate("MainWindow", "OK"))
        self.engine_lbl.setText(_translate("MainWindow", "ENGINE:"))
        self.engine_state_lbl.setText(_translate("MainWindow", "OK"))
        self.radar_lbl.setText(_translate("MainWindow", "RADAR:"))
        self.radar_state_lbl.setText(_translate("MainWindow", "OK"))
        self.fires_lbl.setText(_translate("MainWindow", "FIRES:"))
        self.nb_fire_lbl.setText(_translate("MainWindow", "0"))
        self.repair_but.setText(_translate("MainWindow", "REPAIR"))
        self.menuGame.setTitle(_translate("MainWindow", "Game"))
        self.playerShipsDW.setWindowTitle(_translate("MainWindow", "SHIPS"))
        self.actionNew_Game.setText(_translate("MainWindow", "New Game"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
